name: mir-kiosk-dosbox-x
adopt-info: dosbox-x
summary:  DOSBox-X in kiosk mode
base: core20
description: |
  DOSBox-X is a x86 emulator with Tandy/Hercules/CGA/EGA/VGA/SVGA graphics
  sound and DOS. It's been designed to run old DOS games under platforms that
  don't support it.

architectures:
  - build-on: amd64
  - build-on: armhf

confinement: strict
grade: devel

apps:
  mir-kiosk-dosbox-x:
    daemon: simple
    command-chain:
      - env-setup
    command: bin/desktop-launch $SNAP/usr/local/bin/x11_kiosk_launch $SNAP/dosbox-x
    plugs: [network, network-bind, unity7, opengl, home, audio-playback, desktop, desktop-legacy, removable-media, wayland]

parts:
  dosbox-x:
    plugin: autotools
    source-type: git
    source: https://github.com/joncampbell123/dosbox-x.git
    override-build: |
        # There is no pattern in the release tags for DosBox-X
        # This should resolve to a version or datestamp or both.
        last_committed_tag="$(git describe --tags --abbrev=0)"
        last_committed_tag_ver="$(echo ${last_committed_tag} | sed -e 's/dosbox-x-//' -e 's/wip-//' -e 's/windows-//' -e 's/v//')"
        last_released_tag="$( (snap info mir-kiosk-dosbox-x || true) | awk '$1 == "latest/beta:" { print $2 }')"
        # If the latest tag from the upstream project has not been released to
        # beta, build that tag instead of master.
        if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
          git fetch
          git checkout "${last_committed_tag}"
        fi
        ./autogen.sh || exit 1
        ./configure --enable-core-inline --prefix=/usr --enable-sdl2 || exit 1
        make -j3 || exit 1
        cp src/dosbox-x $SNAPCRAFT_PART_INSTALL
        snapcraftctl set-version $(head -n 1 CHANGELOG | awk -F ' ' '{print $1}' | tr -d '\r')
    build-packages:
      - automake
      - gcc
      - g++
      - libasound2-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavformat-dev
      - libfreetype-dev
      - libfluidsynth-dev
      - libncurses-dev
      - libpcap-dev
      - libpng-dev
      - libpulse-dev
      - libsdl2-dev
      - libsdl2-net-dev
      - libswscale-dev
      - libxkbfile-dev
      - libxrandr-dev
      - make
      - nasm
    stage-packages:
      - fluidsynth
      - freeglut3
      - libasound2
      - libavcodec-extra
      - libavcodec-extra58
      - libavdevice58
      - libavformat58
      - libfluidsynth2
      - libfreetype6
      - libglib2.0-bin
      - libglu1-mesa
      - libncursesw6
      - libpcap0.8
      - libpng16-16
      - libpulse0
      - libsdl2-2.0-0
      - libsdl2-net-2.0-0
      - libswscale5
      - libxkbfile1
      - libxrandr2
    stage-snaps: [mir-kiosk-x11]

  desktop-glib-only:
    build-packages:
      - libglib2.0-dev
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    stage:
      - bin/desktop-launch

# Needed by Mir and/or Xwayland
layout:
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/bin/xkbcomp:
    symlink: $SNAP/usr/bin/xkbcomp
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts
